version: '3'
services:
    web:
        build: ./mitglied_web
        ports: 
            - "8080:80"
        links:
            - php
        volumes:
            - application:/usr/share/nginx/html

    php:
        build: ./mitglied_web/docker_php
        volumes:
            - application:/usr/share/nginx/html

    ldap-server:
        build: ./structure
        ports: 
            - "389:389"
        environment:
            - LDAP_DOMAIN=ldap-provider.fablab-luebeck
            - LDAP_BASE_DN=dc=ldap-provider,dc=fablab-luebeck

volumes:
    application:
        driver: local
