---
- name: Setup Mqtt Host
  hosts: mqtt-host
  become: yes
  vars:
    domains:
      - domain: mqtt.fablab-luebeck.de
        target_ip: 192.168.8.202
        certificate: yes
  tasks:
    - name: Place certificate download script
      template:
        src: ../downloadCertificates.sh.j2
        dest: /root/scripts/downloadCertificates.sh
    - name: Update script permissions
      file:
        path: /root/scripts/downloadCertificates.sh
        mode: 700
        owner: root
        group: root
        state: file
    - name: Enable certificate downloads
      cron:
        name: certificates download
        minute: 0
        hour: 0
        job: "/root/scripts/downloadCertificates.sh > /var/log/downloadCertificate.log 2>&1 && /usr/sbin/service slapd restart"