---
- name: Printstream setup
  hosts: printstream
  become: yes
  vars:
    path: /root/mjpg-streamer
    full_path: '{{path}}/mjpg-streamer-experimental'
  tasks:

    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - build-essential
          - git
          - imagemagick
          - subversion
          - libv4l-dev
          - cmake
          - libjpeg8-dev
          - gcc
          - g++
    - name: Download software
      git:
        repo: 'https://github.com/jacksonliam/mjpg-streamer'
        dest: '{{ path }}'
        version: ddb69b7b4f114f3c2ca01adf55712792ca8aed43
      notify:
        - "rebuild program"
    - meta: flush_handlers
    - name: Install systemd service
      template:
        src: stream.service.j2
        dest: /etc/systemd/system/stream.service
      notify:
        - "start stream service"
    - name: Install second systemd Service
      template:
        src: stream2.service.j2
        dest: /etc/systemd/system/stream2.service
      notify:
        - "start second stream service"
  handlers:
    - name: build program
      make:
        chdir: '{{ full_path }}'
      listen: "rebuild program"
    - name: install program
      make:
        chdir: '{{ full_path }}'
        target: install
      listen: "rebuild program"
    - name: start stream service
      systemd:
        name: stream
        enabled: yes
        daemon_reload: yes
    - name: start second stream service
      systemd:
        name: stream2
        enabled: yes
        daemon_reload: yes
