version: '3'
services:
    web:
        build: .
        ports: 
            - "8080:80"
        links:
            - php
        volumes:
            - application:/usr/share/nginx/html

    php:
        build: ./docker_php
        volumes:
            - application:/usr/share/nginx/html

volumes:
    application:
        driver: local