---
- name: LDAP Authentication
  hosts: all
  become: yes
  vars:
    ldap_base: dc=ldap-provider,dc=fablab-luebeck
  tasks:

    - name: Install pam_ldap
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - libnss-ldapd
        - libpam-ldap
        - nscd
        - portmap
        - nslcd
        - vim
        - sssd
        - libsss-sudo
        - libpam-ssh
    - name: Install sssd-common for mint systems
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - sssd-common
        - ldap-utils
        - libsss-sudo
      when: host_system is defined and host_system == 'mint'
    - name: write common-auth
      template:
        src: common-auth.j2
        dest: /etc/pam.d/common-auth
      notify:
      - restart services
    - name: write common-account
      template:
        src: common-account.j2
        dest: /etc/pam.d/common-account
      notify:
      - restart services
    - name: write common-password
      template:
        src: common-password.j2
        dest: /etc/pam.d/common-password
      notify:
      - restart services
    - name: write common-session
      template:
        src: common-session.j2
        dest: /etc/pam.d/common-session
      notify:
      - restart services
    - name: write pam-ldap config
      template:
        src: ldap.j2
        dest: /etc/pam_ldap.conf
        group: root
        owner: root
        mode: 0700
      notify:
      - restart services
    - name: configure nss-ldap
      template:
        src: ldap.j2
        dest: /etc/libnss-ldap.conf
        group: root
        owner: root
        mode: 0700
      notify:
      - restart services
    - name: configure nss
      template:
        src: nsswitch.j2
        dest: /etc/nsswitch.conf
      notify:
      - restart services
    - name: configure ldap config
      template:
        src: ldap.j2
        dest: /etc/ldap.conf
        group: www-data
        owner: root
        mode: 0750
      notify:
      - restart services
    - name: to be safe use old config path, too
      template:
        src: ldap.j2
        dest: /etc/ldap/ldap.conf
        group: www-data
        owner: root
        mode: 0750
      notify:
      - restart services
    - name: configure nslcd config
      template:
        src: nslcd.j2
        dest: /etc/nslcd.conf
      notify:
      - restart services
    - name: configure sssd config
      template:
        src: sssd.j2
        dest: /etc/sssd/sssd.conf
        group: root
        owner: root
        mode: 0700
      notify:
      - restart services
    - name: enable sssd in ssh config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AuthorizedKeysCommand '
        line: 'AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys'
      notify:
      - restart services
    - name: perform sssd as nobody
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AuthorizedKeysCommandUser '
        line: 'AuthorizedKeysCommandUser nobody'
    - name: disable nscd for hosts
      lineinfile:
        path: /etc/nscd.conf
        regexp: 'enable-cache[ \t]+passwd'
        line: 'enable-cache passwd no'
      notify:
      - restart services
    - name: disable nscd for groups
      lineinfile:
        path: /etc/nscd.conf
        regexp: 'enable-cache[ \t]+group'
        line: 'enable-cache group no'
      notify:
      - restart services
    - name: disable nscd for netgroup
      lineinfile:
        path: /etc/nscd.conf
        regexp: 'enable-cache[ \t]+netgroup'
        line: 'enable-cache netgroup no'
      notify:
      - restart services
  handlers:
    - name: restart services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nscd
        - portmap
        - nslcd
        - sssd
        - ssh
