---
- name: Setup nagios server and clients
  hosts: nagios-monitoring,nagios
  become: yes
  tasks:
    - name: Install nrpe on clients
      when: inventory_hostname in groups["nagios-monitoring"]
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - nagios-nrpe-server
          - nagios-plugins
      notify:
      - restart client services
    - name: Configure nrpe on clients
      when: inventory_hostname in groups["nagios-monitoring"]
      template:
        src: nrpe-client.conf.j2
        dest: /etc/nagios/nrpe.cfg
      notify:
      - restart client services
    - name: Add nrpe commands to clients
      when: inventory_hostname in groups["nagios-monitoring"]
      lineinfile:
        path: /etc/nagios/nrpe.cfg
        insertafter: ^command\[check_total_procs\]
        line: command[{{item.command_name}}]={{item.command}}
        regexp: ^command\[{{item.command_name}}]\=
      with_items:
        - { command_name: check_swap, command: "/usr/lib/nagios/plugins/check_swap -w 35% -c 20%"}
        - { command_name: check_disk, command: "/usr/lib/nagios/plugins/check_disk -w 25% -c 10% -p /"}
        - { command_name: check_procs, command: "/usr/lib/nagios/plugins/check_procs -w 250 -c 400 -s RSZDT"}
        - { command_name: check_load, command: "/usr/lib/nagios/plugins/check_load -r -w 60.0,50.0,40.0 -c 90.0,60.0,50.0"}
      notify:
      - restart client services
    - name: Add nrpe command on server
      when: inventory_hostname == "nagios"
      template:
        src: nrpe-command-server.cfg.j2
        dest: /usr/local/nagios/etc/objects/nrpe-command.cfg
      notify:
      - restart server services
    - name: Add nrpe hosts configuration on server
      when: inventory_hostname == "nagios"
      template:
        src: nrpe-hosts-server.cfg.j2
        dest: /usr/local/nagios/etc/objects/ansible-hosts.cfg
      notify:
      - restart server services
    - name: Enable additional nagios config files
      when: inventory_hostname == "nagios"
      lineinfile:
        path: /usr/local/nagios/etc/nagios.cfg
        insertafter: ^cfg_file=\/usr\/local\/nagios\/etc\/objects\/hosts\.cfg$
        line: cfg_file=/usr/local/nagios/etc/objects/{{ item }}.cfg
      with_items:
        - nrpe-command
        - ansible-hosts
      notify:
      - restart server services
  handlers:
    - name: restart client services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nagios-nrpe-server
    - name: restart server services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nagios
