---
- name: Setup nagios server and clients
  hosts: nagios_monitoring,nagios
  become: yes
  vars:
    contacts:
      - { name: 'Ian', email: 'poesse@fablab-luebeck.de' }
  tasks:
    - name: Install nrpe on clients
      when: inventory_hostname in groups["nagios_monitoring"]
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - nagios-nrpe-server
          - nagios-plugins
          - python3-jmespath
      notify:
      - restart client services
    - name: Configure nrpe on clients
      when: inventory_hostname in groups["nagios_monitoring"]
      template:
        src: nrpe-client.conf.j2
        dest: /etc/nagios/nrpe.cfg
      notify:
      - restart client services
    - name: Add nrpe commands to clients
      when: inventory_hostname in groups["nagios_monitoring"]
      lineinfile:
        path: /etc/nagios/nrpe.cfg
        insertafter: ^command\[check_total_procs\]
        line: command[{{item.command_name}}]={{item.command}}
        regexp: ^command\[{{item.command_name}}]\=
      with_items:
        - { command_name: check_swap, command: "/usr/lib/nagios/plugins/check_swap -w 35% -c 20%"}
        - { command_name: check_disk, command: "/usr/lib/nagios/plugins/check_disk -w 25% -c 10% -p /"}
        - { command_name: check_procs, command: "/usr/lib/nagios/plugins/check_procs -w 250 -c 400 -s RSZDT"}
        - { command_name: check_load, command: "/usr/lib/nagios/plugins/check_load -r -w 0.7,0.6,0.5 -c 0.9,0.8,0.7"}
      notify:
      - restart client services
    - name: Add nrpe command on server
      when: inventory_hostname == "nagios"
      template:
        src: nrpe-command-server.cfg.j2
        dest: /usr/local/nagios/etc/objects/nrpe-command.cfg
      notify:
      - restart server services
    - name: Add nrpe hosts configuration on server
      when: inventory_hostname == "nagios"
      template:
        src: nrpe-hosts-server.cfg.j2
        dest: /usr/local/nagios/etc/objects/ansible-hosts.cfg
      notify:
      - restart server services
    - name: Add contact configuration on server
      when: inventory_hostname == "nagios"
      template:
        src: contact-groups-server.cfg.j2
        dest: /usr/local/nagios/etc/objects/ansible-contacts.cfg
      notify:
      - restart server services
    - name: Enable additional nagios config files
      when: inventory_hostname == "nagios"
      lineinfile:
        path: /usr/local/nagios/etc/nagios.cfg
        insertafter: ^cfg_file=\/usr\/local\/nagios\/etc\/objects\/hosts\.cfg$
        line: cfg_file=/usr/local/nagios/etc/objects/{{ item }}.cfg
      with_items:
        - nrpe-command
        - ansible-hosts
        - ansible-contacts
      notify:
      - restart server services
    - name: Install packages on nagios host
      when: inventory_hostname == "nagios"
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - git
          - pip
    - name: Download check_mqtt plugin from github
      when: inventory_hostname == "nagios"
      ansible.builtin.git:
        repo: https://github.com/jpmens/check-mqtt.git
        dest: /usr/local/check_mqtt
    - name: Install python requirements for check_mqtt
      when: inventory_hostname == "nagios"
      pip:
        requirements: /usr/local/check_mqtt/requirements.txt
    - name: Copy ca.crt file to check_mqtt
      when: inventory_hostname == "nagios"
      template:
        src: ca.crt.j2
        dest: /usr/local/check_mqtt/ca.crt 
        owner: nagios
        group: nagios
  handlers:
    - name: restart client services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nagios-nrpe-server
    - name: restart server services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nagios
