---
- name: Setup old LDAP-Webinterface and dns server
  hosts: ldap-web:ldap-provider
  become: yes
  vars:
    domains:
# Remember to place a dns rebind protection exception in your router!
    - domain: login.fablab-luebeck.de
      target_ip: 192.168.8.211
      certificate: yes
    - domain: einweisungen.fablab-luebeck.de
      target_ip: 192.168.8.211
      certificate: yes
    - domain: ldap-provider.fablab-luebeck.de
      target_ip: 192.168.8.211
      certificate: yes
    - domain: mqtt.fablab-luebeck.de
      target_ip: 192.168.8.202
      certificate: no
    bind9count: 03
    mqtt: no
  tasks:
    - name: Add apt repositories
      apt_repository:
        repo: ppa:ondrej/php
        state: present
      when: inventory_hostname in groups['ldap-web']
    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - apache2
        - php7.2
        - libapache2-mod-php7.2
        - php7.2-mysql
        - default-jre
        - tomcat8
        - maven
        - bind9
      when: inventory_hostname in groups['ldap-web']
    - name: Setup custom domains in bind9
      template:
        src: bind9.j2
        dest: /etc/bind/db.{{item.domain}}
      loop: "{{ domains }}"
      notify: restart services
      when: inventory_hostname in groups['ldap-web']
    - name: Install new Zone in bind9
      template:
        src: named.conf.local.j2
        dest: /etc/bind/named.conf.local
      notify: restart services
      when: inventory_hostname in groups['ldap-web']
    - name: Ensure DNS forwarding
      lineinfile:
        path: /etc/bind/named.conf.options
        regexp: "^forwarders "
        insertafter: "options {"
        #firstmatch: yes
        line: "forwarders {8.8.8.8;};"
      notify: restart services
      when: inventory_hostname in groups['ldap-web']
    - name: Ensure recursive DNS
      lineinfile:
        path: /etc/bind/named.conf.options
        regexp: "^allow-recursion "
        insertafter: "options {"
        line: "allow-recursion {any;};"
      notify: restart services
      when: inventory_hostname in groups['ldap-web']
    - name: Create script path
      file:
        path: /root/scripts
        owner: root
        group: root
        mode: 770
        state: directory
    - name: Place certificate download script
      template:
        src: ../downloadCertificates.sh.j2
        dest: /root/scripts/downloadCertificates.sh
    - name: Update script permissions
      file:
        path: /root/scripts/downloadCertificates.sh
        mode: 700
        owner: root
        group: root
        state: file
    - name: Enable certificate downloads
      cron:
        name: certificates download
        minute: 0
        hour: 0
        job: "/root/scripts/downloadCertificates.sh > /var/log/downloadCertificate.log 2>&1"
  handlers:
    - name: restart services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - bind9
      when: inventory_hostname in groups['ldap-web']
